### ISSUE TITLE
Formulate Requirements

### ISSUE THREAD

**Issue by ijager** [JitterCompany/f1-led-circuit#3]
Currently, we know the high level requirements vaguely. But we should write them down in a detailed and testable/measurable way.

**Comment by CodingInGreen** [comment]
**Requirements**

- 20 LEDS for starting grid
- Countdown timer
- Connects to Wifi for any user's router
- Get a dataset outside of the system
- Have method to distinguish drivers
- Handle scenario where a car is out of race
- PCB shuts down if a maximum temperature is reached
- Passes standard EMC/ESD tests
- On/Off Button for User
- Start/Stop Button for User
- Show visual state of program - running or not
- Firmware should know its own version
- Firmware should be able to detect PCB version
- Debuggable with RTT
- Wall outlet to USB-C adapter
- LED driver is safe
