### ISSUE TITLE
Remove unnecessary components

### ISSUE THREAD

**Issue by ijager** [JitterCompany/f1-led-circuit#42]
- JTAG connector (But perhaps we can expose these pins with some test points on the backside)
- JP1 jumper: same, expose with testpoints
- Boot button: expose pin via test-point

Let's go for standard 2.54 pitch between these test points.

Place all test points in a row close to the board edge to be used with a test clip.

[https://www.fshh1688.com/1-27mm-pitch-test-stand-pcb-clip-clamp-fixture-fixture-probe[…]-program-burn-2pin-3pin-4pin-5pin-6pin-7pin-8pin-9pin-10pin/](https://www.fshh1688.com/1-27mm-pitch-test-stand-pcb-clip-clamp-fixture-fixture-probe-pogo-pin-download-program-burn-2pin-3pin-4pin-5pin-6pin-7pin-8pin-9pin-10pin/)

**Comment by CodingInGreen** [comment]
I added changed those items to test points in the schematic, can you check them and let me know if they are correct?

**Comment by CodingInGreen** [comment]
I've updated the PCB layout, just pushed the changes. 

I'm not sure if there is a standard order for the test points to be in, or if the layout order for the test points matters?

Can you take a quick look when you have a chance?

**Comment by ijager** [comment]
This looks an extra GND and 3V3 testpoint to the JTAG series

**Comment by CodingInGreen** [comment]
Ok added! Let me know if we can close this issue please. Thanks!
